advanced-config: false
created-at: 1711467921950048835
created-by: root
modified-at: 1711468121750221770
modified-by: root
production-ready: false
project-container-name: shakespeare-searcher
project-name: shakespeare-searcher
